{{- if eq .Values.ingress.enabled true }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  sources:
    - repoURL: {{ .Values.ingress.repoURL }}
      chart: {{ .Values.ingress.chart }}
      targetRevision: {{ .Values.ingress.version }}
      helm:
        values: |-
          {{- include "omitNulls" .Values.ingress.config | nindent 10 }}
        releaseName: nginx-ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
